sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.up2pay':
            up2pay_config:
                template: '@ViniumSyliusPayumUp2PayPlugin/admin/payment_method/_up2pay.html.twig'
                priority: 0

        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.up2pay':
            up2pay_config:
                template: '@ViniumSyliusPayumUp2PayPlugin/admin/payment_method/_up2pay.html.twig'
                priority: 0
